# Generated by Django 6.0.4 on 2026-04-24 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('steam', 'Steam'), ('gog', 'GOG'), ('epic', 'Epic Games')], default='steam', max_length=16)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discount_percent', models.IntegerField(default=0)),
                ('deal_url', models.URLField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='library.game')),
            ],
            options={
                'indexes': [models.Index(fields=['-discount_percent'], name='deals_deal_discoun_d1f3a4_idx')],
                'unique_together': {('game', 'platform')},
            },
        ),
    ]
