# Generated by Django 5.2.13 on 2026-04-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='category',
            field=models.CharField(choices=[('specials', '할인 특가'), ('top_sellers', '인기 게임'), ('new_releases', '인기 신작'), ('itad', 'ITAD')], default='specials', max_length=16),
        ),
    ]
