# Generated by Django 5.2.13 on 2026-04-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_deal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='category',
            field=models.CharField(choices=[('specials', '할인 특가'), ('top_sellers', '인기 게임'), ('new_releases', '인기 신작'), ('free', '무료 게임'), ('popular', '인기 게임')], default='specials', max_length=16),
        ),
        migrations.AlterField(
            model_name='deal',
            name='platform',
            field=models.CharField(choices=[('steam', 'Steam'), ('gog', 'GOG'), ('epic', 'Epic Games'), ('directgames', '다이렉트게임즈')], default='steam', max_length=16),
        ),
    ]
