# Generated by Django 6.0.4 on 2026-04-24 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('avatar_url', models.URLField(blank=True)),
                ('profile_updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='steam_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
