# Generated by Django 6.0.4 on 2026-04-24 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpicAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epic_account_id', models.CharField(blank=True, max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('library_updated_at', models.DateTimeField(blank=True, null=True)),
                ('steam_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='epic_account', to='accounts.steamuser')),
            ],
        ),
    ]
