# Generated by Django 5.2.13 on 2026-04-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_epicaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EpicAccount',
        ),
    ]
